media:
  input: src/content/posts
  output: /src/content/posts

content:
  - name: posts
    label: 博客文章
    path: src/content/posts
    type: collection
    view:
      fields: [title, pubDate, description]
      sort: field:pubDate, direction:desc
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      - name: pubDate
        label: 发布日期
        type: datetime
        required: true
      - name: description
        label: 描述
        type: string
      - name: tags
        label: 标签
        type: list
      - name: body
        label: 内容
        type: rich-text
        format: markdown
